const furnitureItems = [
  {
    id: "FURNS001",
    name: "Sofa",
    material: "Fabric",
    color: "Gray",
    price: 500,
    brand: "ComfortHome",
    image: require("./assets/images/SofaGrey.jpg"),
  },
  {
    id: "FURNS002",
    name: "Sofa",
    material: "Leather",
    color: "Black",
    price: 600,
    brand: "LuxLiving",
    image: require("./assets/images/Sofa.jpg"),
  },
  {
    id: "FURNT001",
    name: "Dining Table",
    material: "Wood",
    color: "Brown",
    price: 700,
    brand: "WoodWorks",
    image: require("./assets/images/DiningTableBrown.jpg"),
  },
  {
    id: "FURNT002",
    name: "Dining Table",
    material: "Glass",
    color: "Transparent",
    price: 800,
    brand: "GlassLine",
    image: require("./assets/images/DiningTable.jpg"),
  },
  {
    id: "FURNC001",
    name: "Office Chair",
    material: "Leather",
    color: "Black",
    price: 200,
    brand: "ErgoPro",
    image: require("./assets/images/OfficeChairBlack.jpg"),
  },
  {
    id: "FURNC002",
    name: "Office Chair",
    material: "Fabric",
    color: "Gray",
    price: 180,
    brand: "SitWell",
    image: require("./assets/images/OfficeChair.jpg"),
  },
  {
    id: "FURNB001",
    name: "Bed",
    material: "Wood",
    color: "White",
    price: 1000,
    brand: "DreamZone",
    image: require("./assets/images/BedWhite.jpg"),
  },
  {
    id: "FURNB002",
    name: "Bed",
    material: "Metal",
    color: "Black",
    price: 1200,
    brand: "SleepTech",
    image: require("./assets/images/Bed.jpg"),
  },
  {
    id: "FURNW001",
    name: "Wardrobe",
    material: "Wood",
    color: "Dark Brown",
    price: 800,
    brand: "ClosetKing",
    image: require("./assets/images/WardrobeDB.jpg"),
  },
  {
    id: "FURNW002",
    name: "Wardrobe",
    material: "Wood",
    color: "Light Brown",
    price: 850,
    brand: "StyleCabinet",
    image: require("./assets/images/Wardrobe.jpg"),
  },
  {
    id: "FURNM001",
    name: "Bookshelf",
    material: "Metal",
    color: "Gray",
    price: 150,
    brand: "BookNest",
    image: require("./assets/images/Bookshelf.jpg"),
  },
  {
    id: "FURNM002",
    name: "Bookshelf",
    material: "Wood",
    color: "Brown",
    price: 180,
    brand: "WoodRead",
    image: require("./assets/images/Bookshelf.jpg"),
  },
  {
    id: "FURNP001",
    name: "Shoe Cabinet",
    material: "Plastic",
    color: "White",
    price: 120,
    brand: "ShoeSavvy",
    image: require("./assets/images/ShoeCabinet.jpg"),
  },
  {
    id: "FURNP002",
    name: "Shoe Cabinet",
    material: "Wood",
    color: "Brown",
    price: 150,
    brand: "EntryStyle",
    image: require("./assets/images/ShoeCabinet.jpg"),
  },
  {
    id: "FURNF001",
    name: "Coffee Table",
    material: "Wood",
    color: "Yellow",
    price: 250,
    brand: "BrewSpace",
    image: require("./assets/images/CoffeeTable.jpg"),
  },
  {
    id: "FURNF002",
    name: "Coffee Table",
    material: "Glass",
    color: "Clear",
    price: 300,
    brand: "ClearDesign",
    image: require("./assets/images/CoffeeTable.jpg"),
  },
  {
    id: "FURNB003",
    name: "Armchair",
    material: "Fabric",
    color: "Red",
    price: 400,
    brand: "ChicSit",
    image: require("./assets/images/Armchair, material.jpg"),
  },
  {
    id: "FURNB004",
    name: "Armchair",
    material: "Leather",
    color: "Brown",
    price: 450,
    brand: "EliteRest",
    image: require("./assets/images/Armchair, material.jpg"),
  },
];

export default furnitureItems;
